-- 008 - Seed 25 Turkish MVP recipes (string ingredients, recipe_001..recipe_025)
-- Safe to re-run: upserts on primary key id.

alter table public.recipes
  add column if not exists emoji text not null default '🍽️';

alter table public.recipes
  add column if not exists category_key text not null default 'all';

insert into public.recipes (
  id,
  name,
  emoji,
  category_key,
  ingredients,
  macros,
  time_minutes,
  difficulty,
  steps,
  dietary_tags,
  collections,
  is_premium
) values
(
  'recipe_001',
  'Tavuk Göğsü & Pirinç',
  '🍗',
  'high_protein',
  '["200g tavuk göğsü", "1 su bardağı pirinç", "1 soğan", "2 diş sarımsak", "2 yemek kaşığı zeytinyağı", "tuz, karabiber"]'::jsonb,
  '{"calories": 412, "protein": 35, "carbs": 45, "fat": 8}'::jsonb,
  25,
  'Kolay',
  '["Tavukları doğrayıp tuz ve karabiber ile tatlandırın.", "Pirinci tuzlu suda haşlayın (yaklaşık 15 dakika).", "Zeytinyağında soğan ve sarımsağı soteleyin.", "Tavuğu ekleyip 5 dakika pişirin.", "Haşlanmış pirinci ekleyip karıştırın.", "Sıcak servis edin."]'::jsonb,
  '["high_protein", "halal", "gluten_free"]'::jsonb,
  '["Yüksek Protein", "Öğle Yemeği"]'::jsonb,
  false
),
(
  'recipe_002',
  'Kırmızı Et & Patates',
  '🥩',
  'high_protein',
  '["400g dana kuşbaşı", "4 patates", "2 domates", "1 soğan", "2 yemek kaşığı zeytinyağı", "tuz, karabiber, kimyon"]'::jsonb,
  '{"calories": 612, "protein": 42, "carbs": 38, "fat": 28}'::jsonb,
  50,
  'Orta',
  '["Eti ve patatesi doğrayın.", "Soğanı kavurun, eti ekleyip mühürleyin.", "Domates ve baharatları ekleyin, az su ile kısık ateşte pişirin.", "Patates yumuşayınca servis edin."]'::jsonb,
  '["high_protein", "halal"]'::jsonb,
  '["Yüksek Protein", "Akşam"]'::jsonb,
  false
),
(
  'recipe_003',
  'Balık & Sebze',
  '🐟',
  'high_protein',
  '["250g balık fileto", "1 yeşil biber", "1 domates", "yarım limon", "1 yemek kaşığı zeytinyağı", "defne, tuz"]'::jsonb,
  '{"calories": 380, "protein": 36, "carbs": 12, "fat": 18}'::jsonb,
  22,
  'Kolay',
  '["Fırını 190°C''ye ısıtın.", "Balık ve sebzeleri tepsiye yerleştirin.", "Zeytinyağı ve limon sıkın.", "15–18 dakika pişirin.", "Sıcak servis edin."]'::jsonb,
  '["high_protein", "gluten_free", "halal"]'::jsonb,
  '["Yüksek Protein", "Hafif"]'::jsonb,
  false
),
(
  'recipe_004',
  'Yumurta Omlet (Protein)',
  '🍳',
  'high_protein',
  '["3 yumurta", "40g kaşar veya lor", "1 domates", "1 yeşil biber", "1 çay kaşığı zeytinyağı", "tuz, karabiber"]'::jsonb,
  '{"calories": 340, "protein": 24, "carbs": 8, "fat": 22}'::jsonb,
  12,
  'Çok Kolay',
  '["Yumurtaları çırpın, tuz ekleyin.", "Sebzeleri doğrayıp hafifçe kavurun.", "Karışımı tavaya dökün.", "Altı tutunca peyniri serpin, katlayarak servis edin."]'::jsonb,
  '["high_protein", "vegetarian", "halal"]'::jsonb,
  '["Yüksek Protein", "Kahvaltı"]'::jsonb,
  false
),
(
  'recipe_005',
  'Tavuk Şnitzel & Yoğurt Sosu',
  '🍗',
  'high_protein',
  '["2 tavuk göğsü", "1 yumurta", "4 yemek kaşığı galeta unu", "2 yemek kaşığı yoğurt", "1 diş sarımsak", "zeytinyağı, tuz"]'::jsonb,
  '{"calories": 480, "protein": 38, "carbs": 28, "fat": 22}'::jsonb,
  35,
  'Orta',
  '["Tavukları inceltin, tuzlayın.", "Yumurtaya batırıp galeta ununa bulayın.", "Kızgın yağda her iki yüzünü kızartın.", "Yoğurda sarımsak ve tuz ekleyerek sos yapın.", "Şnitzel ile servis edin."]'::jsonb,
  '["high_protein", "halal"]'::jsonb,
  '["Yüksek Protein", "Akşam"]'::jsonb,
  false
),
(
  'recipe_006',
  'Kıymalı Sebzeler (High Protein)',
  '🥘',
  'high_protein',
  '["250g yağsız kıyma", "2 patlıcan veya kabak", "1 soğan", "2 domates", "2 yemek kaşığı zeytinyağı", "tuz, karabiber, kırmızı biber"]'::jsonb,
  '{"calories": 420, "protein": 32, "carbs": 18, "fat": 24}'::jsonb,
  40,
  'Kolay',
  '["Sebzeleri doğrayın.", "Kıymayı kavurun, sebzeleri ekleyin.", "Domates ve baharatla soteleyin.", "Kapağı kapatıp 15 dakika pişirin.", "Maydanoz ile servis edin."]'::jsonb,
  '["high_protein", "halal", "gluten_free"]'::jsonb,
  '["Yüksek Protein", "Tek Tencere"]'::jsonb,
  false
),
(
  'recipe_007',
  'Mercimek Çorbası',
  '🥣',
  'vegan',
  '["1 su bardağı kırmızı mercimek", "1 soğan", "1 havuç", "1 küçük patates", "1 yemek kaşığı zeytinyağı", "1 çay kaşığı kimyon, tuz"]'::jsonb,
  '{"calories": 240, "protein": 14, "carbs": 36, "fat": 6}'::jsonb,
  35,
  'Kolay',
  '["Mercimeği yıkayın.", "Soğan ve havucu kavurun.", "Mercimek ve patatesi ekleyip su ile haşlayın.", "Blendır ile pürüzsüz yapın.", "Limon ve nane ile servis edin."]'::jsonb,
  '["vegan", "vegetarian", "halal", "gluten_free"]'::jsonb,
  '["Çorba", "Vegan Haftası"]'::jsonb,
  false
),
(
  'recipe_008',
  'Kale Salatası & Tahini Sosu',
  '🥗',
  'vegan',
  '["150g kale", "1 avuç cherry domates", "yarım salatalık", "2 yemek kaşığı tahin", "yarım limon suyu", "2 yemek kaşığı zeytinyağı", "tuz"]'::jsonb,
  '{"calories": 220, "protein": 8, "carbs": 16, "fat": 14}'::jsonb,
  15,
  'Kolay',
  '["Kaleyi ince doğrayıp ovalayın.", "Sebzeleri doğrayın.", "Tahin, limon, zeytinyağı ve tuzla sos hazırlayın.", "Tümünü harmanlayıp hemen servis edin."]'::jsonb,
  '["vegan", "vegetarian", "gluten_free"]'::jsonb,
  '["Vegan Haftası", "Hafif"]'::jsonb,
  false
),
(
  'recipe_009',
  'Nohut Köfte & Salata',
  '🧆',
  'vegan',
  '["400g haşlanmış nohut", "yarım demet maydanoz", "3 yemek kaşığı un veya galeta", "1 soğan", "kimyon, tuz, karabiber", "zeytinyağı"]'::jsonb,
  '{"calories": 360, "protein": 16, "carbs": 52, "fat": 10}'::jsonb,
  45,
  'Orta',
  '["Nohutu çatalla ezin veya robotta çekin.", "Soğan ve maydanozu ince doğrayın.", "Harçı yoğurup köfte şekli verin.", "Fırında veya az yağda kızartın.", "Yeşil salata ile servis edin."]'::jsonb,
  '["vegan", "vegetarian", "halal", "gluten_free"]'::jsonb,
  '["Vegan Haftası", "Öğle Yemeği"]'::jsonb,
  false
),
(
  'recipe_010',
  'Kişi Mantısı (Vegan Uyumlu)',
  '🥟',
  'vegan',
  '["manti hamuru veya yufka", "200g vegan kıyma veya mantarlı harç", "1 soğan", "2 yemek kaşığı domates salçası", "zeytinyağı, nane, tuz"]'::jsonb,
  '{"calories": 410, "protein": 14, "carbs": 58, "fat": 14}'::jsonb,
  55,
  'Zor',
  '["Harcı soğanla soteleyin.", "Hamura doldurup kapatın.", "Fırında veya tavada pişirin.", "Salçalı sos ve nane ile servis edin."]'::jsonb,
  '["vegan", "vegetarian"]'::jsonb,
  '["Vegan Haftası", "Akşam"]'::jsonb,
  false
),
(
  'recipe_011',
  'Zucchini Noodles & Pesto',
  '🥒',
  'low_carb',
  '["2 kabak", "2 yemek kaşığı pesto", "1 yemek kaşığı zeytinyağı", "parmesan veya vegan peynir", "tuz, karabiber"]'::jsonb,
  '{"calories": 290, "protein": 12, "carbs": 10, "fat": 22}'::jsonb,
  18,
  'Kolay',
  '["Kabakları spiral kesin.", "Tavada az yağda 2 dakika soteleyin.", "Pesto ve baharatla karıştırın.", "Peynir serperek servis edin."]'::jsonb,
  '["keto", "low_carb", "vegetarian", "gluten_free"]'::jsonb,
  '["Düşük Karbonhidrat", "Hızlı"]'::jsonb,
  false
),
(
  'recipe_012',
  'Tavuk & Kremalı Sos',
  '🍗',
  'low_carb',
  '["300g tavuk göğsü", "100ml krema veya süzme yoğurt", "1 diş sarımsak", "1 yemek kaşığı tereyağı", "tuz, karabiber, kekik"]'::jsonb,
  '{"calories": 450, "protein": 40, "carbs": 6, "fat": 28}'::jsonb,
  30,
  'Orta',
  '["Tavuğu doğrayıp baharatlayın.", "Tereyağında kavurun.", "Sarımsak ve kremayı ekleyin.", "Kısık ateşte koyulaşana kadar pişirin.", "Sıcak servis edin."]'::jsonb,
  '["keto", "high_protein", "gluten_free", "halal"]'::jsonb,
  '["Düşük Karbonhidrat", "Akşam"]'::jsonb,
  false
),
(
  'recipe_013',
  'Yumurta Muffins (Keto)',
  '🧁',
  'low_carb',
  '["4 yumurta", "60g peynir", "1 yeşil biber", "yarım soğan", "tuz, karabiber"]'::jsonb,
  '{"calories": 280, "protein": 20, "carbs": 6, "fat": 18}'::jsonb,
  25,
  'Kolay',
  '["Fırını 180°C''ye ısıtın.", "Yumurtaları çırpın, sebze ve peyniri ekleyin.", "Kalıplara paylaştırın.", "18–20 dakika pişirin."]'::jsonb,
  '["keto", "low_carb", "high_protein", "vegetarian"]'::jsonb,
  '["Düşük Karbonhidrat", "Kahvaltı"]'::jsonb,
  false
),
(
  'recipe_014',
  'Ispanak & Feta Salatası',
  '🥗',
  'low_carb',
  '["150g ıspanak", "80g feta", "10 zeytin", "1 yemek kaşığı zeytinyağı", "limon suyu", "tuz, karabiber"]'::jsonb,
  '{"calories": 320, "protein": 14, "carbs": 8, "fat": 26}'::jsonb,
  12,
  'Çok Kolay',
  '["Ispanağı yıkayın.", "Feta ve zeytini ekleyin.", "Zeytinyağı ve limonla soslayın.", "Karıştırıp servis edin."]'::jsonb,
  '["keto", "low_carb", "vegetarian", "gluten_free"]'::jsonb,
  '["Düşük Karbonhidrat", "Hafif"]'::jsonb,
  false
),
(
  'recipe_015',
  '5 Dakikalık Omlet',
  '⚡',
  'quick',
  '["2 yumurta", "30g peynir", "1 çay kaşığı tereyağı", "tuz"]'::jsonb,
  '{"calories": 280, "protein": 18, "carbs": 2, "fat": 20}'::jsonb,
  5,
  'Çok Kolay',
  '["Yumurtaları çırpın.", "Tereyağını tavada eritin.", "Karışımı döküp 2 dakika pişirin.", "Peyniri serpip katlayın."]'::jsonb,
  '["high_protein", "vegetarian", "halal"]'::jsonb,
  '["5 Dakika", "Öğrenci"]'::jsonb,
  false
),
(
  'recipe_016',
  'Açık Sandwich (Tuna)',
  '🥪',
  'quick',
  '["2 dilim tam buğday ekmek", "1 küçük konserve ton balığı", "1 yemek kaşığı yoğurt veya mayonez", "marul, domates", "limon, tuz, karabiber"]'::jsonb,
  '{"calories": 380, "protein": 28, "carbs": 32, "fat": 14}'::jsonb,
  8,
  'Çok Kolay',
  '["Ton balığını süzün ve yoğurtla karıştırın.", "Ekmekleri kızartın.", "Marul ve domatesi yerleştirin.", "Balık karışımını üstüne yayın ve servis edin."]'::jsonb,
  '["high_protein", "halal"]'::jsonb,
  '["5 Dakika", "Öğle Yemeği"]'::jsonb,
  false
),
(
  'recipe_017',
  'Instant Noodle Upgrade (Sağlıklı)',
  '🍜',
  'quick',
  '["1 paket noodle", "1 yumurta", "1 avuç ıspanak veya lahana", "1 yemek kaşığı soya sosu", "susam, yeşil soğan"]'::jsonb,
  '{"calories": 420, "protein": 16, "carbs": 52, "fat": 16}'::jsonb,
  12,
  'Kolay',
  '["Noodle''u pakete göre haşlayın.", "Ayrı bir tavada yumurtayı pişirin.", "Sebzeleri noodle''a ekleyin.", "Soya sosu ve susamla tatlandırın."]'::jsonb,
  '["vegetarian", "halal"]'::jsonb,
  '["5 Dakika", "Bütçe Dostu"]'::jsonb,
  false
),
(
  'recipe_018',
  'Stir-Fry (Quick & Easy)',
  '🥢',
  'quick',
  '["200g tavuk veya tofu", "karışık donmuş sebze", "2 yemek kaşığı soya sosu", "1 diş sarımsak", "zeytinyağı veya susam yağı"]'::jsonb,
  '{"calories": 400, "protein": 30, "carbs": 28, "fat": 18}'::jsonb,
  15,
  'Kolay',
  '["Proteini ince şerit doğrayın.", "Tavayı çok ısıtın, yağı ekleyin.", "Önce proteini, sonra sebzeleri soteleyin.", "Soya sosu ve sarımsakla bitirin."]'::jsonb,
  '["high_protein", "gluten_free", "halal"]'::jsonb,
  '["5 Dakika", "Öğle Yemeği"]'::jsonb,
  false
),
(
  'recipe_019',
  'Pasta (Simple Tomato)',
  '🍝',
  'quick',
  '["150g makarna", "2 domates veya 1 su bardağı domates sosu", "2 diş sarımsak", "2 yemek kaşığı zeytinyağı", "tuz, fesleğen"]'::jsonb,
  '{"calories": 480, "protein": 14, "carbs": 72, "fat": 14}'::jsonb,
  20,
  'Kolay',
  '["Makarnayı haşlayın.", "Sarımsaklı domates sosunu pişirin.", "Haşlanmış makarnayı sosla karıştırın.", "Fesleğen ile servis edin."]'::jsonb,
  '["vegetarian", "halal"]'::jsonb,
  '["5 Dakika", "Akşam"]'::jsonb,
  false
),
(
  'recipe_020',
  'Yoğurt Bowl & Granola',
  '🥣',
  'breakfast',
  '["200g yoğurt", "3 yemek kaşığı granola", "yarım muz", "1 yemek kaşığı bal veya hurma", "tarçın"]'::jsonb,
  '{"calories": 380, "protein": 14, "carbs": 48, "fat": 12}'::jsonb,
  7,
  'Çok Kolay',
  '["Yoğurdu kaseye alın.", "Üzerine granola ve meyveyi ekleyin.", "Bal ve tarçın serpin.", "Hemen tüketin."]'::jsonb,
  '["vegetarian", "halal", "gluten_free"]'::jsonb,
  '["Kahvaltı", "Hızlı"]'::jsonb,
  false
),
(
  'recipe_021',
  'Smoothie Bowl (Protein)',
  '🫐',
  'breakfast',
  '["1 muz", "yarım su bardağı yaban mersini", "1 ölçü protein tozu", "yarım su bardağı süt veya badem sütü", "2 yemek kaşığı yulaf"]'::jsonb,
  '{"calories": 340, "protein": 28, "carbs": 38, "fat": 8}'::jsonb,
  10,
  'Kolay',
  '["Tüm malzemeleri blendırda pürüzsüz yapın.", "Kaseye dökün.", "Üzerine meyve ve yulaf serpin."]'::jsonb,
  '["high_protein", "vegetarian", "gluten_free"]'::jsonb,
  '["Kahvaltı", "Protein"]'::jsonb,
  false
),
(
  'recipe_022',
  'Menemen (Turkish Scramble)',
  '🍳',
  'breakfast',
  '["3 yumurta", "2 domates", "2 yeşil biber", "1 yemek kaşığı zeytinyağı", "tuz, karabiber"]'::jsonb,
  '{"calories": 360, "protein": 20, "carbs": 14, "fat": 24}'::jsonb,
  18,
  'Kolay',
  '["Sebzeleri küp doğrayın.", "Zeytinyağında soteleyin.", "Yumurtaları kırıp karıştırın.", "Kıvamlı olunca sıcak servis edin."]'::jsonb,
  '["high_protein", "vegetarian", "halal", "gluten_free"]'::jsonb,
  '["Kahvaltı", "Tek Tencere"]'::jsonb,
  false
),
(
  'recipe_023',
  'Hummus & Sebzeler',
  '🫓',
  'snack',
  '["400g haşlanmış nohut", "2 yemek kaşığı tahin", "2 diş sarımsak", "3 yemek kaşığı zeytinyağı", "1 limon suyu", "havuç ve salatalık çubukları"]'::jsonb,
  '{"calories": 360, "protein": 14, "carbs": 36, "fat": 18}'::jsonb,
  15,
  'Kolay',
  '["Nohut, tahin, sarımsak ve limonu blend edin.", "Zeytinyağı ile kıvam verin.", "Sebzelerle servis edin."]'::jsonb,
  '["vegan", "vegetarian", "halal", "gluten_free"]'::jsonb,
  '["Atıştırmalık", "Meze"]'::jsonb,
  false
),
(
  'recipe_024',
  'Protein Energy Balls',
  '🌰',
  'snack',
  '["1 su bardağı yulaf", "yarım su bardağı fıstık ezmesi", "2 yemek kaşığı bal", "2 yemek kaşığı protein tozu", "1 yemek kaşığı kakao"]'::jsonb,
  '{"calories": 280, "protein": 18, "carbs": 28, "fat": 10}'::jsonb,
  20,
  'Kolay',
  '["Kuru malzemeleri karıştırın.", "Bal ile yoğurun.", "Top şekli verin.", "Buzdolabında 30 dakika dinlendirin."]'::jsonb,
  '["high_protein", "vegetarian", "gluten_free"]'::jsonb,
  '["Atıştırmalık", "Meal Prep"]'::jsonb,
  false
),
(
  'recipe_025',
  'Quinoa & Roasted Vegetables',
  '🥙',
  'balanced',
  '["yarım su bardağı kinoa", "karışık fırın sebzesi (biber, kabak, patlıcan)", "2 yemek kaşığı zeytinyağı", "limon, tuz, kekik"]'::jsonb,
  '{"calories": 440, "protein": 16, "carbs": 52, "fat": 18}'::jsonb,
  35,
  'Orta',
  '["Kinoayı haşlayın.", "Sebzeleri zeytinyağı ve baharatla fırınlayın.", "Kasede harmanlayın.", "Limon sıkıp servis edin."]'::jsonb,
  '["vegan", "vegetarian", "gluten_free", "halal"]'::jsonb,
  '["Dengeli Beslenme", "Öğle Yemeği"]'::jsonb,
  false
)
on conflict (id) do update set
  name = excluded.name,
  emoji = excluded.emoji,
  category_key = excluded.category_key,
  ingredients = excluded.ingredients,
  macros = excluded.macros,
  time_minutes = excluded.time_minutes,
  difficulty = excluded.difficulty,
  steps = excluded.steps,
  dietary_tags = excluded.dietary_tags,
  collections = excluded.collections,
  is_premium = excluded.is_premium;
