-- 011 - seed recipes from lib/data/default_recipes.dart
-- Adds missing columns used by the app (emoji, category_key) and upserts 25 recipes.

alter table public.recipes
add column if not exists emoji text not null default '🍽️';

alter table public.recipes
add column if not exists category_key text not null default 'all';

insert into public.recipes (
  id,
  name,
  emoji,
  category_key,
  ingredients,
  macros,
  time_minutes,
  difficulty,
  steps,
  dietary_tags,
  collections,
  is_premium
)
values
(
  'recipe_1',
  'Tavuk & Pirinç',
  '🍗',
  'high_protein',
  '[{"name":"Chicken","amount":"300 g"},{"name":"Rice","amount":"1 cup dry"},{"name":"Onion","amount":"1 pcs"},{"name":"Garlic","amount":"2 cloves"},{"name":"Olive Oil","amount":"2 tbsp"}]'::jsonb,
  '{"calories":520,"protein":42,"carbs":48,"fat":14}'::jsonb,
  25,
  'Kolay',
  '["Tavuğu küp doğrayıp tuz ve karabiberle marine et.","Pirinci yıka; soğan ve sarımsağı kavur, tavuğu ekle.","Pirinci ekle, sıcak su ile pişir ve kısık ateşte demle.","Maydanoz ile servis et."]'::jsonb,
  '["high_protein","halal","gluten_free"]'::jsonb,
  '["Yüksek Protein","Öğle Yemeği"]'::jsonb,
  false
),
(
  'recipe_2',
  'Kırmızı Et & Patates',
  '🥩',
  'high_protein',
  '[{"name":"Beef","amount":"400 g"},{"name":"Potato","amount":"4 pcs"},{"name":"Onion","amount":"1 pcs"},{"name":"Olive Oil","amount":"2 tbsp"},{"name":"Tomato","amount":"2 pcs"}]'::jsonb,
  '{"calories":610,"protein":48,"carbs":38,"fat":28}'::jsonb,
  40,
  'Orta',
  '["Eti kuşbaşı doğra, patatesi dilimle.","Tencerede soğanı kavur, eti ekleyip mühürle.","Domates ve baharatları ekle, su ilave et.","Patatesi ekle ve kısık ateşte yumuşayana kadar pişir."]'::jsonb,
  '["high_protein","halal","keto"]'::jsonb,
  '["Yüksek Protein","Akşam"]'::jsonb,
  false
),
(
  'recipe_3',
  'Balık & Sebze',
  '🐟',
  'high_protein',
  '[{"name":"Fish Fillet","amount":"250 g"},{"name":"Green Pepper","amount":"1 pcs"},{"name":"Tomato","amount":"1 pcs"},{"name":"Lemon","amount":"1 pcs"},{"name":"Olive Oil","amount":"1 tbsp"}]'::jsonb,
  '{"calories":380,"protein":36,"carbs":12,"fat":18}'::jsonb,
  22,
  'Kolay',
  '["Fırını 190 °C’ye ısıt.","Balık ve sebzeleri tepsiye diz, zeytinyağı ve limon sık.","15–18 dakika pişir.","Sıcak servis et."]'::jsonb,
  '["high_protein","gluten_free","halal"]'::jsonb,
  '["Yüksek Protein","Hafif"]'::jsonb,
  false
),
(
  'recipe_4',
  'Tofu & Makarna',
  '🍝',
  'high_protein',
  '[{"name":"Tofu","amount":"200 g"},{"name":"Pasta","amount":"150 g"},{"name":"Tomato","amount":"2 pcs"},{"name":"Garlic","amount":"2 cloves"},{"name":"Olive Oil","amount":"1 tbsp"}]'::jsonb,
  '{"calories":480,"protein":28,"carbs":58,"fat":14}'::jsonb,
  20,
  'Kolay',
  '["Tofuyu küp doğra ve kızart.","Sarımsaklı domates sosunu hazırla.","Makarnayı haşla ve sosla karıştır.","Üzerine tofu ve fesleğen ekle."]'::jsonb,
  '["vegan","high_protein","vegetarian"]'::jsonb,
  '["Vegan Haftası","Öğle Yemeği"]'::jsonb,
  false
),
(
  'recipe_5',
  'Yumurta Omlet',
  '🍳',
  'high_protein',
  '[{"name":"Eggs","amount":"3 pcs"},{"name":"Cheese","amount":"40 g"},{"name":"Tomato","amount":"1 pcs"},{"name":"Green Pepper","amount":"1 pcs"},{"name":"Olive Oil","amount":"1 tsp"}]'::jsonb,
  '{"calories":340,"protein":24,"carbs":8,"fat":22}'::jsonb,
  12,
  'Kolay',
  '["Yumurtaları çırp, tuz ekle.","Sebzeleri doğra ve hafif kavur.","Karışımı dök ve altını tutunca peyniri serp.","Katlayarak servis et."]'::jsonb,
  '["high_protein","vegetarian","halal"]'::jsonb,
  '["Yüksek Protein","Kahvaltı"]'::jsonb,
  false
),
(
  'recipe_6',
  'Mercimek Çorbası',
  '🥣',
  'vegan',
  '[{"name":"Red Lentils","amount":"1 cup"},{"name":"Onion","amount":"1 pcs"},{"name":"Carrot","amount":"1 pcs"},{"name":"Olive Oil","amount":"1 tbsp"},{"name":"Potato","amount":"1 pcs"}]'::jsonb,
  '{"calories":240,"protein":14,"carbs":36,"fat":6}'::jsonb,
  35,
  'Kolay',
  '["Mercimeği yıka.","Soğan ve havucu kavur, mercimek ve patatesi ekle.","Su ekle kaynat, ezerek kıvam ver.","Limon ve nane ile servis et."]'::jsonb,
  '["vegan","vegetarian","halal","gluten_free"]'::jsonb,
  '["Çorba","Vegan Haftası"]'::jsonb,
  false
),
(
  'recipe_7',
  'Kale Salatası',
  '🥗',
  'vegan',
  '[{"name":"Kale","amount":"150 g"},{"name":"Tomato","amount":"1 pcs"},{"name":"Cucumber","amount":"1 pcs"},{"name":"Olive Oil","amount":"2 tbsp"},{"name":"Lemon","amount":"½ pcs"}]'::jsonb,
  '{"calories":180,"protein":6,"carbs":14,"fat":12}'::jsonb,
  15,
  'Kolay',
  '["Kaleyi doğra ve ovala.","Sebzeleri küp doğra.","Zeytinyağı ve limonla sos hazırla.","Karıştır ve hemen servis et."]'::jsonb,
  '["vegan","vegetarian","gluten_free"]'::jsonb,
  '["Vegan Haftası","Hafif"]'::jsonb,
  false
),
(
  'recipe_8',
  'Kabak Noodle',
  '🥒',
  'low_carb',
  '[{"name":"Zucchini","amount":"2 pcs"},{"name":"Chicken","amount":"150 g"},{"name":"Garlic","amount":"2 cloves"},{"name":"Olive Oil","amount":"1 tbsp"},{"name":"Tomato","amount":"1 pcs"}]'::jsonb,
  '{"calories":290,"protein":32,"carbs":10,"fat":12}'::jsonb,
  18,
  'Kolay',
  '["Kabakları spiral kes.","Tavuğu baharatla sotele.","Sarımsak ve domatesi ekle.","Kabak noodle ile hızlıca karıştır."]'::jsonb,
  '["low_carb","keto","gluten_free"]'::jsonb,
  '["Düşük Karbonhidrat","Hızlı"]'::jsonb,
  false
),
(
  'recipe_9',
  'Yumurta Muffin',
  '🧁',
  'low_carb',
  '[{"name":"Eggs","amount":"4 pcs"},{"name":"Cheese","amount":"60 g"},{"name":"Green Pepper","amount":"1 pcs"},{"name":"Onion","amount":"½ pcs"},{"name":"Salt","amount":"To taste"}]'::jsonb,
  '{"calories":260,"protein":20,"carbs":6,"fat":16}'::jsonb,
  25,
  'Kolay',
  '["Fırını 180 °C’ye ısıt.","Yumurtaları çırp, sebze ve peyniri ekle.","Kalıplara paylaştır.","18–20 dakika pişir."]'::jsonb,
  '["low_carb","keto","high_protein"]'::jsonb,
  '["Düşük Karbonhidrat","Kahvaltı"]'::jsonb,
  false
),
(
  'recipe_10',
  '5 Dakika Omlet',
  '⚡',
  'quick',
  '[{"name":"Eggs","amount":"2 pcs"},{"name":"Cheese","amount":"30 g"},{"name":"Butter","amount":"1 tsp"},{"name":"Salt","amount":"To taste"}]'::jsonb,
  '{"calories":280,"protein":18,"carbs":2,"fat":20}'::jsonb,
  5,
  'Kolay',
  '["Yumurtaları çırp.","Tereyağını tavada erit.","Karışımı dök, 2 dakika pişir.","Peyniri serp, katla ve servis et."]'::jsonb,
  '["vegetarian","high_protein","halal"]'::jsonb,
  '["5 Dakika","Öğrenci"]'::jsonb,
  false
),
(
  'recipe_11',
  'Izgara Köfte & Bulgur',
  '🧆',
  'dinner',
  '[{"name":"Ground Beef","amount":"400 g"},{"name":"Onion","amount":"1 pcs"},{"name":"Bulgur","amount":"1 cup"},{"name":"Parsley","amount":"1 bunch"},{"name":"Olive Oil","amount":"2 tbsp"}]'::jsonb,
  '{"calories":640,"protein":44,"carbs":42,"fat":30}'::jsonb,
  35,
  'Orta',
  '["Köftelik harcı yoğur.","Köfteleri ızgarada pişir.","Bulgur pilavını hazırla.","Salata ile servis et."]'::jsonb,
  '["high_protein","halal"]'::jsonb,
  '["Akşam","Yüksek Protein"]'::jsonb,
  true
),
(
  'recipe_12',
  'Nohut Yemeği',
  '🫘',
  'vegan',
  '[{"name":"Chickpeas","amount":"400 g canned"},{"name":"Onion","amount":"1 pcs"},{"name":"Tomato","amount":"2 pcs"},{"name":"Olive Oil","amount":"2 tbsp"},{"name":"Garlic","amount":"3 cloves"}]'::jsonb,
  '{"calories":420,"protein":18,"carbs":58,"fat":12}'::jsonb,
  45,
  'Kolay',
  '["Soğanı kavur.","Baharat ve domatesi ekle.","Nohutu ekle ve kısık ateşte pişir.","Maydanoz ile servis et."]'::jsonb,
  '["vegan","vegetarian","halal","gluten_free"]'::jsonb,
  '["Vegan Haftası","Tek Tencere"]'::jsonb,
  true
),
(
  'recipe_13',
  'Sebzeli Mercimek',
  '🍲',
  'vegan',
  '[{"name":"Green Lentils","amount":"1 cup"},{"name":"Carrot","amount":"2 pcs"},{"name":"Onion","amount":"1 pcs"},{"name":"Potato","amount":"2 pcs"},{"name":"Olive Oil","amount":"1 tbsp"}]'::jsonb,
  '{"calories":360,"protein":16,"carbs":54,"fat":8}'::jsonb,
  30,
  'Kolay',
  '["Mercimeği haşla.","Sebzeleri doğra ve sotele.","Karıştır ve baharatla.","Kıvamlı olunca servis et."]'::jsonb,
  '["vegan","vegetarian","gluten_free"]'::jsonb,
  '["Vegan Haftası","Öğle Yemeği"]'::jsonb,
  true
),
(
  'recipe_14',
  'Fırında Tavuk But',
  '🍗',
  'high_protein',
  '[{"name":"Chicken","amount":"600 g"},{"name":"Potato","amount":"4 pcs"},{"name":"Garlic","amount":"6 cloves"},{"name":"Olive Oil","amount":"3 tbsp"},{"name":"Thyme","amount":"1 tsp"}]'::jsonb,
  '{"calories":560,"protein":52,"carbs":32,"fat":22}'::jsonb,
  50,
  'Orta',
  '["Fırını 200 °C’ye ısıt.","Tavuk ve patatesi marine et.","Fırın tepsisine diz.","45 dakika kızarana kadar pişir."]'::jsonb,
  '["high_protein","keto","halal","gluten_free"]'::jsonb,
  '["Yüksek Protein","Akşam"]'::jsonb,
  true
),
(
  'recipe_15',
  'Levrek Buğulama',
  '🐠',
  'dinner',
  '[{"name":"Sea Bass","amount":"400 g"},{"name":"Lemon","amount":"2 pcs"},{"name":"Parsley","amount":"1 bunch"},{"name":"Olive Oil","amount":"2 tbsp"},{"name":"Onion","amount":"1 pcs"}]'::jsonb,
  '{"calories":340,"protein":38,"carbs":8,"fat":16}'::jsonb,
  28,
  'Orta',
  '["Balığı temizle.","Soğan halkaları ve limonla tepsiye yerleştir.","Buharda veya fırında pişir.","Zeytinyağı gezdirerek servis et."]'::jsonb,
  '["high_protein","gluten_free","halal"]'::jsonb,
  '["Akşam","Hafif"]'::jsonb,
  true
),
(
  'recipe_16',
  'Kabak Spagetti Bolonez',
  '🍅',
  'low_carb',
  '[{"name":"Zucchini","amount":"3 pcs"},{"name":"Ground Beef","amount":"250 g"},{"name":"Tomato","amount":"3 pcs"},{"name":"Garlic","amount":"3 cloves"},{"name":"Olive Oil","amount":"1 tbsp"}]'::jsonb,
  '{"calories":420,"protein":36,"carbs":14,"fat":24}'::jsonb,
  32,
  'Orta',
  '["Kabaktan spaghetti şekli çıkar.","Kıymalı sosu pişir.","Kabakları hızlıca sotele.","Sosla karıştır ve servis et."]'::jsonb,
  '["low_carb","keto","gluten_free"]'::jsonb,
  '["Düşük Karbonhidrat","Akşam"]'::jsonb,
  true
),
(
  'recipe_17',
  'Protein Chia Puding',
  '🫙',
  'quick',
  '[{"name":"Chia Seeds","amount":"3 tbsp"},{"name":"Protein Powder","amount":"1 scoop"},{"name":"Almond Milk","amount":"200 ml"},{"name":"Salt","amount":"pinch"}]'::jsonb,
  '{"calories":310,"protein":28,"carbs":18,"fat":12}'::jsonb,
  10,
  'Kolay',
  '["Tüm malzemeleri çırp.","Kavanoza koy.","Buzdolabında 2 saat beklet.","Meyve ile servis et."]'::jsonb,
  '["high_protein","vegetarian","no_dairy"]'::jsonb,
  '["5 Dakika","Kahvaltı"]'::jsonb,
  true
),
(
  'recipe_18',
  'Fırında Karnabahar',
  '🥦',
  'vegan',
  '[{"name":"Cauliflower","amount":"1 head"},{"name":"Olive Oil","amount":"2 tbsp"},{"name":"Garlic","amount":"4 cloves"},{"name":"Salt","amount":"To taste"}]'::jsonb,
  '{"calories":180,"protein":8,"carbs":14,"fat":12}'::jsonb,
  35,
  'Kolay',
  '["Karnabaharı parçala.","Baharat ve yağla harmanla.","Fırında 25 dakika kızart.","Sos ile servis et."]'::jsonb,
  '["vegan","keto","gluten_free"]'::jsonb,
  '["Vegan Haftası","Atıştırmalık"]'::jsonb,
  true
),
(
  'recipe_19',
  'Tavuklu Quinoa Kasesi',
  '🥙',
  'high_protein',
  '[{"name":"Chicken","amount":"200 g"},{"name":"Quinoa","amount":"½ cup"},{"name":"Cucumber","amount":"1 pcs"},{"name":"Tomato","amount":"1 pcs"},{"name":"Olive Oil","amount":"1 tbsp"}]'::jsonb,
  '{"calories":480,"protein":40,"carbs":38,"fat":14}'::jsonb,
  28,
  'Kolay',
  '["Quinoayı pişir.","Tavuğu baharatla ızgarada pişir.","Sebzeleri doğra.","Kasede birleştir."]'::jsonb,
  '["high_protein","gluten_free","halal"]'::jsonb,
  '["Yüksek Protein","Öğle Yemeği"]'::jsonb,
  true
),
(
  'recipe_20',
  'Humus & Tam Buğday',
  '🫓',
  'vegan',
  '[{"name":"Chickpeas","amount":"400 g"},{"name":"Tahini","amount":"2 tbsp"},{"name":"Garlic","amount":"2 cloves"},{"name":"Olive Oil","amount":"3 tbsp"},{"name":"Lemon","amount":"1 pcs"}]'::jsonb,
  '{"calories":380,"protein":14,"carbs":44,"fat":16}'::jsonb,
  15,
  'Kolay',
  '["Nohutu ve tahini blend et.","Limon ve sarımsak ekle.","Kıvam için su ayarla.","Ekmekle servis et."]'::jsonb,
  '["vegan","vegetarian","halal"]'::jsonb,
  '["Vegan Haftası","Meze"]'::jsonb,
  true
),
(
  'recipe_21',
  'Etli Nohut',
  '🍛',
  'dinner',
  '[{"name":"Beef","amount":"300 g"},{"name":"Chickpeas","amount":"2 cups"},{"name":"Onion","amount":"1 pcs"},{"name":"Tomato","amount":"2 pcs"},{"name":"Olive Oil","amount":"2 tbsp"}]'::jsonb,
  '{"calories":580,"protein":42,"carbs":48,"fat":22}'::jsonb,
  55,
  'Orta',
  '["Eti kavur.","Soğan ve domatesle sotele.","Nohutu ekle ve pişir.","Dinlendirip servis et."]'::jsonb,
  '["high_protein","halal","gluten_free"]'::jsonb,
  '["Akşam","Tek Tencere"]'::jsonb,
  true
),
(
  'recipe_22',
  'Yulaf Ezmesi Bowl',
  '🥣',
  'quick',
  '[{"name":"Oats","amount":"½ cup"},{"name":"Milk","amount":"200 ml"},{"name":"Eggs","amount":"1 pcs"},{"name":"Salt","amount":"pinch"}]'::jsonb,
  '{"calories":340,"protein":16,"carbs":48,"fat":8}'::jsonb,
  12,
  'Kolay',
  '["Yulaf ve sütü pişir.","Yumurtayı haşla ve dilimle.","Kaseye diz.","Baharatla servis et."]'::jsonb,
  '["vegetarian","high_protein"]'::jsonb,
  '["5 Dakika","Kahvaltı"]'::jsonb,
  true
),
(
  'recipe_23',
  'Peynirli Gözleme',
  '🫔',
  'dinner',
  '[{"name":"Flour","amount":"300 g"},{"name":"Cheese","amount":"200 g"},{"name":"Parsley","amount":"½ bunch"},{"name":"Olive Oil","amount":"2 tbsp"}]'::jsonb,
  '{"calories":520,"protein":22,"carbs":58,"fat":22}'::jsonb,
  30,
  'Orta',
  '["Hamuru yoğur.","İç harcı hazırla.","Aç ve sacda pişir.","Sıcak servis et."]'::jsonb,
  '["vegetarian","halal"]'::jsonb,
  '["Öğle Yemeği","Bütçe Dostu"]'::jsonb,
  true
),
(
  'recipe_24',
  'Sebzeli Omlet',
  '🍳',
  'quick',
  '[{"name":"Eggs","amount":"3 pcs"},{"name":"Zucchini","amount":"½ pcs"},{"name":"Tomato","amount":"1 pcs"},{"name":"Cheese","amount":"40 g"},{"name":"Olive Oil","amount":"1 tsp"}]'::jsonb,
  '{"calories":320,"protein":22,"carbs":10,"fat":20}'::jsonb,
  14,
  'Kolay',
  '["Sebzeleri rendele.","Yumurtayla çırp.","Tavada pişir.","Peynirle servis et."]'::jsonb,
  '["vegetarian","high_protein","keto"]'::jsonb,
  '["5 Dakika","Kahvaltı"]'::jsonb,
  true
),
(
  'recipe_25',
  'Antep Fıstıklı Fit Bar',
  '🌰',
  'snack',
  '[{"name":"Pistachio","amount":"100 g"},{"name":"Oats","amount":"1 cup"},{"name":"Honey","amount":"2 tbsp"},{"name":"Salt","amount":"pinch"}]'::jsonb,
  '{"calories":280,"protein":10,"carbs":26,"fat":16}'::jsonb,
  20,
  'Kolay',
  '["Kuru malzemeleri karıştır.","Bal ile bağla.","Kalıba yay ve sıkıştır.","Buzdolabında dilimle."]'::jsonb,
  '["vegetarian","gluten_free"]'::jsonb,
  '["Atıştırmalık","Meal Prep"]'::jsonb,
  true
)
on conflict (id) do update set
  name = excluded.name,
  emoji = excluded.emoji,
  category_key = excluded.category_key,
  ingredients = excluded.ingredients,
  macros = excluded.macros,
  time_minutes = excluded.time_minutes,
  difficulty = excluded.difficulty,
  steps = excluded.steps,
  dietary_tags = excluded.dietary_tags,
  collections = excluded.collections,
  is_premium = excluded.is_premium;

